# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
- '7'

dist: trusty
sudo: required

# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y calibre xvfb

install:
- npm install -g gitbook-cli
- npm install -g gulp
- npm install
- gitbook fetch
- gitbook install

script:
- xvfb-run gulp all
- xvfb-run sh ./.travis/deploy.sh

branches:
  only:
  - master